# Generated by Django 5.0.6 on 2024-07-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenTripMapServiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_longitude', models.FloatField()),
                ('min_latitude', models.FloatField()),
                ('max_longitude', models.FloatField()),
                ('max_latitude', models.FloatField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
