# Generated by Django 5.0.6 on 2024-07-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigrationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('base_url', models.URLField()),
                ('credentials', models.JSONField(default=dict)),
            ],
        ),
    ]
