# Generated by Django 5.1.1 on 2024-12-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
