# Generated by Django 5.0.6 on 2024-07-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='country',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='postal_code',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
