# Generated by Django 5.0.6 on 2024-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_entity_address_alter_entity_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallinks',
            name='website_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='wikipedia_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
