# Generated by Django 5.0.6 on 2024-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_address_alter_activity_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
