# Generated by Django 5.0.6 on 2024-08-22 13:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_externallinks_website_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='point_field',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
