# Generated by Django 5.0.6 on 2024-08-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activitysave'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='wikipedia_url',
            field=models.URLField(null=True),
        ),
    ]
