# Generated by Django 5.0.6 on 2024-08-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activitysave'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
