# Generated by Django 5.0.6 on 2024-08-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_migrate_coordinates_to_pointfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='coordinates',
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
