# Generated by Django 5.0.6 on 2024-08-07 20:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_website_url_activity_wikipedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
    ]
