# Generated by Django 5.0.6 on 2024-09-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_remove_entity_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
    ]
