# Generated by Django 5.1.1 on 2024-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_comment_user_entity_owner_like_user_save_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
