# Generated by Django 5.1.1 on 2024-11-26 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_view_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='view',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_view'),
        ),
    ]
